FROM golang:1.16 as build-env
WORKDIR /go/src/app
COPY . /go/src/app
RUN go get -d -v ./... && go build -o /go/bin/app

FROM gcr.io/distroless/base
COPY --from=build-env /go/bin/app /
COPY ./db/migrations /migrations
CMD ["/app"]
