version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: genbo
  genbo:
    image: baiten.io/genbo:alpha
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      DBUSER: postgres
      DBPASSWORD: pass
      DBNAME: genbo
    build:
      context: .
      dockerfile: ./Dockerfile.local
